sudo: true
dist: trusty

language: c++ 

services:
   - docker

before_install:
   - docker build -t bjpop/hitime .

script:
   - ./hitime-docker.sh -i data/testing.mzML -o data/scored.mzML -- -r 10 -d 6.0201 -m 230
   - ./hitime-docker.sh -i data/scored.mzML -o data/max.scored.mzML -- -r 10 -l 0.3 -u 0.7
