#!/bin/bash
set -e

function show_help {
cat << UsageMessage

hitime: detect twin ion signals in mass spectrometry data

Usage:
    hitime (score|max) args... 

Example:
    hitime score -i input.mzML -o output.mzML 

To get help on command line arguments for 'score' or 'max':

    hitime score -h
    hitime max -h

UsageMessage
}

if [ "$#" -lt 1 ]; then
   echo "hitime error: insufficient command line arguments"
   show_help 
   exit 2
fi

if [ "$1" = 'score' ]; then
    shift 1
    exec score/hitime-score "$@"
elif [ "$1" = 'max' ]; then
    shift 1
    exec maxima/hitime-max "$@"
else
    show_help
    exit 2
fi
